bitjourney/plantuml-service

src/main/kotlin/com/bitjourney/plantuml/Main.kt

Or, give the executable full-path as the 2nd argument.

find graphviz dot executable in the PATH

---

build.gradle
src/main/kotlin/com/bitjourney/plantuml/Main.kt

Because ALB requires `Content-Length` for health check.

set content-length header to responses

---

build.gradle
src/main/kotlin/com/bitjourney/plantuml/Main.kt

https://github.com/ben-manes/caffeine (In-Memory Cache for Java8)
@bitjourney/kibela-developers 👁

Introduce LRU caching

---

README.md
src/main/kotlin/com/bitjourney/plantuml/DataSource.kt
src/main/kotlin/com/bitjourney/plantuml/Main.kt

e.g. `config=scale max 1024 width` sets the scale parameter.
ref. http://plantuml.com/commons (for `scale= parameters)

add "config" params to set configuration

---

build.gradle

upgrade PlantUML to 8049

---

build.gradle

upgrade plantuml to 8053

---

build.gradle
src/main/kotlin/com/bitjourney/plantuml/Main.kt

e.g. `{"PlantUML":"8053","plantuml-service":"1.0.6"}`

include plantuml-service version to /version response

---

build.gradle

upgrade plantuml to v8059

---

build.gradle

https://github.com/plantuml/plantuml/compare/v2017.11...v1.2017.13

upgrade PlantUML to v1.2017.13

---

build.gradle

https://github.com/plantuml/plantuml/compare/v1.2017.15...v1.2017.18
> 1,476 changed files with 309,613 additions and 1,183 deletions.
lol

upgrade plantuml from v1.2017.15 to v1.2017.18

---

build.gradle

changes: http://plantuml.com/changes

upgrade PlantUML to V1.2017.19

---

system.properties

related?: https://github.com/bitjourney/plantuml-service/issues/27

Use the latest JDK on Heroku

---

bin/plantuml-service
src/main/kotlin/com/bitjourney/plantuml/Main.kt

Don't set java.awt.headless by default

---

example/example-salt-tree.plantuml
src/main/kotlin/com/bitjourney/plantuml/Main.kt
src/test/kotlin/com/bitjourney/plantuml/MainTest.kt

fix unnecessary URL decode for params

---

CHANGES.md
build.gradle

Release v1.4.0.
Release v1.4.0.
ref: https://github.com/bitjourney/plantuml-service/commit/beb26168d7389fc23b4e8db83a1fcf55732d17de
Create the credential file by echo "oauth=$GITHUB_ACCESS_TOKEN" > ~/.github
Run`./gradlew release`
ref) https://github.com/bitjourney/plantuml-service#release-engineering

Release v1.4.0

---

DockerfileForDebug
build.gradle

20220823 upgrade packages

---

build.gradle

20220823 upgrade packages 2

---

README.md

[bitjourney/homebrew-self](https://github.com/bitjourney/homebrew-self) has been archived.
So I removed its mentions from README.

Remove mentions of Homebrew Tap which has been archived

---

Dockerfile
DockerfileForDebug

Upgrade base image for vulnerability
ref) https://github.com/adoptium/containers/issues/275

Upgrade base image

---

src/main/kotlin/com/bitjourney/plantuml/Main.kt

Fix import path. Changes between 1.2023.1 and 1.2023.2
ref
https://github.com/plantuml/plantuml/commit/75835ce2a0d047bfa3ebe62b8da773f86e66113c

Move dot folder under plantuml

---

release.gradle

Change container registory system to ghcr from Docker Hub

Change registory to ghcr

---

.tool-versions
build.gradle

Fix this message
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main"
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
```
---------------------
Fix java version to make it the same with docker container.

Exclude meta-inf files and fix java version

---

DockerfileForBuild
README.md

Add docker file for build jar

---

src/main/kotlin/com/bitjourney/plantuml/Main.kt

The method has been changed to match the changes in the next commit.
https://github.com/plantuml/plantuml/commit/f09a9afeb3585435a9451ca2654dc7c1419cffad
https://github.com/plantuml/plantuml/commit/4e83c1a0cc0f1717079f2bb605d40f9542946ad2

Change due to version upgrade

---

CHANGES.md
build.gradle

- **Add platforms linux/arm64**
- **Release 1.4.20**

kuroponzu/relase 1.4.20
